apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets-provider
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/project-pubsub-32009/secrets/webapp-api-token/versions/latest"
        fileName: "API_KEY"